version: "3"

# networks:
#   front_net:
#     ipam:
#       driver: default
#       config:
#         - subnet: "10.0.0.1/24"
networks:
  mq:
    driver: bridge
  db:
    driver: bridge
  migration:
    driver: bridge
  rotation:
    driver: bridge
      

services:
  mq:
    image: rabbitmq:3.8.17-management-alpine
    ports:
      - "15672:15672"
    expose:
      # - 15672
      - 5672
    restart: always
    # networks:
    #   front_net:
    #     ipv4_address: 10.0.0.4
    #     aliases: 
    #       - mq
    networks:
      - mq
      - rotation


  db:
    # image: postgres:9.6-alpine
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    # networks:
    #   front_net:
    #     ipv4_address: 10.0.0.2
    #     aliases: 
    #       - db
    networks:
      - db
      - migration

  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    depends_on:
      - db
    restart: on-failure
    # networks:
    #   front_net:
    #     ipv4_address: 10.0.0.3
    #     aliases: 
    #       - migration
    networks:
      - migration
      - db


  rotation:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - migration
    ports:
      - "50051:50051"
    restart: on-failure
    # networks:
    #   front_net:
    #     ipv4_address: 10.0.0.5
    #     aliases: 
    #       - rotation
    networks:
      - rotation
      - db
      - mq

          # переделываем сети отсюда