logger:
  level : "info"  # you can set: errorlevel / warn / info / debug
  file : "./logs/test.log"

storage:
  connStr : "user=someuser dbname=rotationdb sslmode=disable"
  
GRPCServer:
  hostPort : ":50051"

MQ:
  uri : "amqp://guest:guest@localhost:5672/"
  exchange : "test-exchange"
  reliable : true
  routingKey : "test-key"